# Generated by Django 4.1.5 on 2023-01-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Author Name')),
                ('date_of_birth', models.DateField(verbose_name='Author Date Of Birth')),
                ('country', models.CharField(max_length=100, verbose_name="Author's Country")),
            ],
        ),
    ]
